
spring:
  jpa:
#    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-34-227-135-211.compute-1.amazonaws.com/d2fp5j7dae7ffv
    username: nrwsvdslgzvbmi
    password: ee0e9fee344cfe92310b8e65e99c3005dc59b87d8d36257cb21dcf5df6f35d97
    platform: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  secret-key: kwj_test_sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms : 2592000000
